# ---------- Base ----------
FROM node:20-alpine AS base
WORKDIR /app

# ---------- Builder ----------
FROM base AS builder
RUN apk add --no-cache git

ARG REPO_URL=https://github.com/Q-Niranjan/openg2p-registry-core-ui.git
ARG GIT_BRANCH=develop

# Clone repo
RUN git clone --branch ${GIT_BRANCH} --depth 1 ${REPO_URL} .

# ---- Cache npm install layer ----
COPY package.json package-lock.json ./
RUN npm ci

# ---- Copy rest of source & build ----
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ---------- Runner ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# Copy built app
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy core locales (overridden by ConfigMap at runtime)
COPY --from=builder --chown=nextjs:nodejs /app/locales ./locales

# Runtime dependency required by Next/Image
RUN npm install sharp

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
